version: "3.9"

services:
  my_chatbot_api:
    build:
      context: .
      dockerfile: Docker/api.Dockerfile
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    ports:
      - "8000:8000"


  my_chatbot_ui:
    build: 
      context: .
      dockerfile: Docker/ui.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      medical_chatbot_api:
        condition: service_healthy
  